name: spa_management
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  pdf: ^3.6.0
  path_provider: ^2.0.5
  image_picker: ^0.8.4+2
  google_maps_flutter: ^2.1.1
  webview_flutter: ^3.0.0
  charts_flutter: ^0.12.0
  charts_common: ^0.12.0
  http: ^0.13.4
  shared_preferences: ^2.0.8
  datetime_picker_formfield: ^1.0.0
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.5
  google_sign_in: ^5.0.1
  flutter_facebook_auth: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
